### ISSUE TITLE
Handle case of call to self-destructed DApp

### ISSUE THREAD

**Issue by jeff-aion** [aionnetwork/AVM#343]
Sending a call to a self-destructed DApp instance results in this exception:

```
java.lang.NullPointerException

	at org.aion.avm.core.persistence.ContractEnvironmentState.loadFromGraph(ContractEnvironmentState.java:12)

	at org.aion.avm.core.DAppExecutor.call(DAppExecutor.java:33)

	at org.aion.avm.core.AvmImpl.commonInvoke(AvmImpl.java:378)

	at org.aion.avm.core.AvmImpl.runExternalInvoke(AvmImpl.java:304)

	at org.aion.avm.core.AvmImpl.backgroundProcessTransaction(AvmImpl.java:213)

	at org.aion.avm.core.AvmImpl.access$200(AvmImpl.java:37)

	at org.aion.avm.core.AvmImpl$AvmExecutorThread.run(AvmImpl.java:87)
```

At first glance, I suspect that the problem is that we are not failing earlier-on, possibly due to the DApp code still being present in the `SoftCache`.  This hypothesis hasn't been verified, however.

**Comment by zhike-aion** [comment]
Reproduce another related error by adding the following test case to SelfDestructTest.java. 
The error output is also attached. 
-----    
@Test
    public void deleteSelfAndReturnValue1() {
        Address target = deployCommonResource(new byte[0]);
        
        byte[] argData = ABIEncoder.encodeMethodArguments("deleteAndReturn", deployer);
        Object resultObject = callDApp(target, argData);
        Assert.assertEquals(SelfDestructResource.DELETE_AND_RETURN, ((Integer)resultObject).intValue());

        avmRule.block = new Block(new byte[32], 2, Helpers.randomAddress(), System.currentTimeMillis(), new byte[0]);
        failToCall(target);
    }
-----
Error output:
FATAL internal error: "Statement MUST be true"
org.aion.avm.internal.RuntimeAssertionError: Statement MUST be true
	at org.aion.avm.internal.RuntimeAssertionError.assertTrue(RuntimeAssertionError.java:22)
	at org.aion.avm.core.persistence.keyvalue.KeyValueObjectGraph.loadRootOnly(KeyValueObjectGraph.java:448)
	at org.aion.avm.core.persistence.keyvalue.KeyValueObjectGraph.getRoot(KeyValueObjectGraph.java:125)
	at org.aion.avm.core.persistence.LoadedDApp.populateClassStaticsFromStorage(LoadedDApp.java:106)
	at org.aion.avm.core.DAppExecutor.call(DAppExecutor.java:66)
	at org.aion.avm.core.AvmImpl.commonInvoke(AvmImpl.java:388)
	at org.aion.avm.core.AvmImpl.runExternalInvoke(AvmImpl.java:313)
	at org.aion.avm.core.AvmImpl.backgroundProcessTransaction(AvmImpl.java:226)
	at org.aion.avm.core.AvmImpl.access$300(AvmImpl.java:37)
	at org.aion.avm.core.AvmImpl$AvmExecutorThread.run(AvmImpl.java:98)

java.lang.AssertionError: org.aion.avm.internal.RuntimeAssertionError: Statement MUST be true

	at org.aion.avm.core.DAppExecutor.call(DAppExecutor.java:193)
	at org.aion.avm.core.AvmImpl.commonInvoke(AvmImpl.java:388)
	at org.aion.avm.core.AvmImpl.runExternalInvoke(AvmImpl.java:313)
	at org.aion.avm.core.AvmImpl.backgroundProcessTransaction(AvmImpl.java:226)
	at org.aion.avm.core.AvmImpl.access$300(AvmImpl.java:37)
	at org.aion.avm.core.AvmImpl$AvmExecutorThread.run(AvmImpl.java:98)
Caused by: org.aion.avm.internal.RuntimeAssertionError: Statement MUST be true
	at org.aion.avm.internal.RuntimeAssertionError.assertTrue(RuntimeAssertionError.java:22)
	at org.aion.avm.core.persistence.keyvalue.KeyValueObjectGraph.loadRootOnly(KeyValueObjectGraph.java:448)
	at org.aion.avm.core.persistence.keyvalue.KeyValueObjectGraph.getRoot(KeyValueObjectGraph.java:125)
	at org.aion.avm.core.persistence.LoadedDApp.populateClassStaticsFromStorage(LoadedDApp.java:106)
	at org.aion.avm.core.DAppExecutor.call(DAppExecutor.java:66)

**Comment by zhike-aion** [comment]
The last BlockchainRuntime.call in this following test case could be probably not correct. The response should be probably null instead of JUST_RETURN. It is in in SelfDestructResource.java.

    public static int callToDeleteSuccess(Address beneficiary, Address target) {
        // Call the target to get them to delete themselves.
        BigInteger value = BigInteger.ZERO;
        byte[] data = ABIEncoder.encodeMethodArguments("deleteAndReturn", beneficiary);
        long energyLimit = BlockchainRuntime.getRemainingEnergy() / 2;
        byte[] response = BlockchainRuntime.call(target, value, data, energyLimit).getReturnData();
        assert (DELETE_AND_RETURN == (Integer)ABIDecoder.decodeOneObject(response));
        
        // Call back to ourselves, to verify that we are ok.
        data = ABIEncoder.encodeMethodArguments("justReturn");
        energyLimit = BlockchainRuntime.getRemainingEnergy() / 2;
        response = BlockchainRuntime.call(BlockchainRuntime.getAddress(), value, data, energyLimit).getReturnData();
        assert (JUST_RETURN == (Integer)ABIDecoder.decodeOneObject(response));

        // Try to call them, verifying that they are not accessible.
        data = ABIEncoder.encodeMethodArguments("justReturn");
        energyLimit = BlockchainRuntime.getRemainingEnergy() / 2;
        response = BlockchainRuntime.call(target, value, data, energyLimit).getReturnData();
        assert (JUST_RETURN == (Integer)ABIDecoder.decodeOneObject(response));
        return CALL_TO_DELETE_SUCCESS;
    }
