### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/aion/cli/AvmCLI has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by miguelmota** [aionnetwork/AVM#372]
I'm going through the [hello world tutorial](https://docs.aion.network/) and coming across an error:

```bash
$ wget https://github.com/aionnetwork/AVM/releases/download/avmtestnet-2019-02-08/avmtestnet-2019-02-08.tar.bz2
$ tar xvzf avmtestnet-2019-02-08.tar.bz2
$ cd aion/lib
$ java -jar avm.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/aion/cli/AvmCLI has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

I'm on macOS and not the most familiar with Java. Any help is appreciated. Thanks

**Comment by jeff-aion** [comment]
That error means that you have JDK8 and the AVM requires JDK10.  You will need to make sure that you have at least JDK10 installed and that it is the one your system is trying to use (you can verify this on the command line with `java -version` to see the version and then `which java` will show you where the one you are using is installed).

**Comment by miguelmota** [comment]
Thanks! Updating to JDK11 fixed it.
